name: Atualizar data de modificação em arquivos Markdown

on:
  push:
    paths:
      - "README.md"
      - "docs/**/*.md"

jobs:
  update_date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Wiki repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT_WRITE_DOCS }}

      - name: Atualizar data nos arquivos modificados
        run: |
          export TZ=America/Sao_Paulo
          git fetch origin main
          MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(README\.md|docs/.*\.md)$' || true)

          if [ -z "$MODIFIED_FILES" ]; then
            echo "Nenhum arquivo .md em /docs ou o README.md foi modificado. Encerrando workflow."
            exit 0
          fi

          for FILE_PATH in $MODIFIED_FILES; do
            echo "Atualizando data em: $FILE_PATH"
            LAST_MODIFIED=$(date +"%Y-%m-%d %H:%M:%S (America/Sao_Paulo)")

            if grep -q "^\*\*Última modificação em:\*\*" "$FILE_PATH"; then
              sed -i "s|^\*\*Última modificação em:\*\*.*|**Última modificação em:** $LAST_MODIFIED|" "$FILE_PATH"
            else
              echo -e "\n---\n**Última modificação em:** $LAST_MODIFIED" >> "$FILE_PATH"
            fi

            git add "$FILE_PATH"
          done

          git config --global user.name "prfs91"
          git config --global user.email "71240638+prfs91@users.noreply.github.com"

          git commit -m "📚 docs(workflow): Update last modified date in markdown files" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT_WRITE_DOCS }}@github.com/prfs91/VolunteerCodeCarajas.git
          git push
